sudo: false
dist: trusty

language: python

cache: apt

addons:
  apt:
    packages:
    - libsaxonb-java
    - inkscape
    - default-jre

install:
    - wget http://files.basex.org/releases/8.6.1/BaseX861.zip && unzip BaseX861.zip && rm BaseX861.zip
    - export PATH=$PATH:$PWD/basex/bin

script: make maps && tar czvf output.tar.gz output

cache:
  directories:
    - $PWD/data

deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file: "output.tar.gz"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    recipients:
      - lucas.gautheron@gmail.com
    on_success: change # default: change
on_failure: always
